using System.IO;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using QuestPDF.Helpers;
using Hotel.Domain.Features.Billing.Entities;

namespace Hotel.Infrastructure.Features.Billing.Services
{
    public static class InvoicePdfService
    {
        public static byte[] Generate(Invoice inv)
        {
            // Configure QuestPDF license. Change to LicenseType.Commercial if required by your org.
            QuestPDF.Settings.License = LicenseType.Community;

            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor("#FFFFFF");
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .Text($"Invoice {inv.InvoiceNumber}")
                        .SemiBold().FontSize(20).FontColor("#2563eb");

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Booking ID: {inv.BookingId}");
                        col.Item().Text($"Created: {inv.CreatedAt:yyyy-MM-dd HH:mm} UTC");
                        col.Item().Text($"Status: {inv.Status}");

                        col.Item().Text($"Nights: {inv.Nights}");
                        col.Item().Text($"Nightly Rate: {inv.NightlyRate:C}");
                        col.Item().Text($"Subtotal: {inv.Subtotal:C}");

                        if (inv.PaidAt != null)
                            col.Item().Text($"Paid At: {inv.PaidAt:yyyy-MM-dd HH:mm} UTC");
                    });

                    page.Footer().AlignCenter().Text("Hotel Management MVP - Generated by API");
                });
            });

            using var ms = new MemoryStream();
            doc.GeneratePdf(ms);
            return ms.ToArray();
        }
    }
}
